baseURL = "/"
languageCode = "en-us"
title = "Oakville Windows and Doors"

[markup.goldmark.renderer]
    unsafe= true

[params]
    description="OWD"

[menu]
    [[menu.main]]
        name = "HOME"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "WINDOWS"
        url = "/windows/"
        weight = 2

    [[menu.main]]
        name = "DOORS"
        url = "/doors/"
        weight = 3

    [[menu.main]]
        name = "REPAIRS"
        url = "/repairs/"
        weight = 4

    [[menu.main]]
        name = "CONTACT"
        url = "/contact/"
        weight = 5

    [[menu.main]]
        name = "COMMERCIAL"
        url = "/commercial/"
        weight = 6

    [[menu.main]]
        name = "GALLERY"
        url = "/gallery/"
        weight = 7

    [[menu.main]]
        name = "BLOG"
        url = "/blog/"
        weight = 8

    [[menu.main]]
        name = "TESTIMONIALS"
        url = "/testimonials/"
        weight = 9

